name: 'SleepFixer'
version: '${project.version}'
description: '${project.description}'
authors: [ 'lokka30' ]
website: 'https://github.com/lokka30/SleepFixer'
load: 'STARTUP'
main: 'io.github.arcaneplugins.sleepfixer.SleepFixer'
api-version: '1.13'
# Yes, api-version is intentionally set to the older version, '1.13'.
# It suppresses the 'legacy' warning whilst still working on all MC versions
# that the plugin intends to support (1.7+ as of writing).
